import { MultiplierType } from "./multipliertype";

export const coordinatesToMultiplierType: Record<string, MultiplierType> = {
    // Triple words
    "A1": MultiplierType.Word,
    "H1": MultiplierType.Word,
    "O1": MultiplierType.Word,
    "A8": MultiplierType.Word,
    "O8": MultiplierType.Word,
    "A15": MultiplierType.Word,
    "H15": MultiplierType.Word,
    "O15": MultiplierType.Word,
    // Double words
    "B2": MultiplierType.Word,
    "N2": MultiplierType.Word,
    "C3": MultiplierType.Word,
    "M3": MultiplierType.Word,
    "D4": MultiplierType.Word,
    "L4": MultiplierType.Word,
    "E5": MultiplierType.Word,
    "K5": MultiplierType.Word,
    "H8": MultiplierType.Word,
    "E11": MultiplierType.Word,
    "K11": MultiplierType.Word,
    "D12": MultiplierType.Word,
    "L12": MultiplierType.Word,
    "C13": MultiplierType.Word,
    "M13": MultiplierType.Word,
    "B14": MultiplierType.Word,
    "N14": MultiplierType.Word,
    // Triple letters
    "F2": MultiplierType.Letter,
    "J2": MultiplierType.Letter,
    "B6": MultiplierType.Letter,
    "F6": MultiplierType.Letter,
    "J6": MultiplierType.Letter,
    "N6": MultiplierType.Letter,
    "B10": MultiplierType.Letter,
    "F10": MultiplierType.Letter,
    "J10": MultiplierType.Letter,
    "N10": MultiplierType.Letter,
    "F14": MultiplierType.Letter,
    "J14": MultiplierType.Letter,
    // Double letters
    "D1": MultiplierType.Letter,
    "L1": MultiplierType.Letter,
    "G3": MultiplierType.Letter,
    "I3": MultiplierType.Letter,
    "A4": MultiplierType.Letter,
    "H4": MultiplierType.Letter,
    "O4": MultiplierType.Letter,
    "C7": MultiplierType.Letter,
    "G7": MultiplierType.Letter,
    "I7": MultiplierType.Letter,
    "M7": MultiplierType.Letter,
    "D8": MultiplierType.Letter,
    "L8": MultiplierType.Letter,
    "C9": MultiplierType.Letter,
    "G9": MultiplierType.Letter,
    "I9": MultiplierType.Letter,
    "M9": MultiplierType.Letter,
    "A12": MultiplierType.Letter,
    "H12": MultiplierType.Letter,
    "O12": MultiplierType.Letter,
    "G13": MultiplierType.Letter,
    "I13": MultiplierType.Letter,
    "D15": MultiplierType.Letter,
    "L15": MultiplierType.Letter,
};

