import { Multiplier } from "./multiplier";

export const coordinatesToMultiplier: Record<string, Multiplier> = {
    // Triple words
    "A1": Multiplier.Triple,
    "H1": Multiplier.Triple,
    "O1": Multiplier.Triple,
    "A8": Multiplier.Triple,
    "O8": Multiplier.Triple,
    "A15": Multiplier.Triple,
    "H15": Multiplier.Triple,
    "O15": Multiplier.Triple,
    // Double words
    "B2": Multiplier.Double,
    "N2": Multiplier.Double,
    "C3": Multiplier.Double,
    "M3": Multiplier.Double,
    "D4": Multiplier.Double,
    "L4": Multiplier.Double,
    "E5": Multiplier.Double,
    "K5": Multiplier.Double,
    "H8": Multiplier.Double,
    "E11": Multiplier.Double,
    "K11": Multiplier.Double,
    "D12": Multiplier.Double,
    "L12": Multiplier.Double,
    "C13": Multiplier.Double,
    "M13": Multiplier.Double,
    "B14": Multiplier.Double,
    "N14": Multiplier.Double,
    // Triple letters
    "F2": Multiplier.Triple,
    "J2": Multiplier.Triple,
    "B6": Multiplier.Triple,
    "F6": Multiplier.Triple,
    "J6": Multiplier.Triple,
    "N6": Multiplier.Triple,
    "B10": Multiplier.Triple,
    "F10": Multiplier.Triple,
    "J10": Multiplier.Triple,
    "N10": Multiplier.Triple,
    "F14": Multiplier.Triple,
    "J14": Multiplier.Triple,
    // Double letters
    "D1": Multiplier.Double,
    "L1": Multiplier.Double,
    "G3": Multiplier.Double,
    "I3": Multiplier.Double,
    "A4": Multiplier.Double,
    "H4": Multiplier.Double,
    "O4": Multiplier.Double,
    "C7": Multiplier.Double,
    "G7": Multiplier.Double,
    "I7": Multiplier.Double,
    "M7": Multiplier.Double,
    "D8": Multiplier.Double,
    "L8": Multiplier.Double,
    "C9": Multiplier.Double,
    "G9": Multiplier.Double,
    "I9": Multiplier.Double,
    "M9": Multiplier.Double,
    "A12": Multiplier.Double,
    "H12": Multiplier.Double,
    "O12": Multiplier.Double,
    "G13": Multiplier.Double,
    "I13": Multiplier.Double,
    "D15": Multiplier.Double,
    "L15": Multiplier.Double,
};

